[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.gd", "php84Extensions.pdo_mysql", "php84Extensions.zip", "php84Extensions.opcache", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
