[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.gd", "php82Extensions.pdo_mysql", "php82Extensions.zip", "php82Extensions.opcache", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
