[providers]
list = ["php"]

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.gd", "php84Extensions.pdo_mysql", "php84Extensions.zip", "php84Extensions.opcache"]

[phases.build]
cmds = ["php -v", "composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

[variables]
PHP_VERSION = "8.4"
NIXPACKS_PHP_VERSION = "8.4"
NIXPACKS_PHP_EXTENSIONS = "gd,pdo_mysql,zip,opcache"
